# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 8080

spring:
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true
    cache: false
# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: messages
#    cache-seconds: -1
    encoding: UTF-8
# MONGODB (MongoProperties)
  data:
    mongodb:
      host: <hostname>
      port: 27017
      uri: mongodb+srv://<username>:<password>@<hostname>/test?retryWrites=true&w=majority
      database: database
#      authentication-database: mongovwdb
#      grid-fs-database:
#     username: 
#     password: 
#      repositories:
#        enabled: true  # if spring data repository support is enabled

# ENDPOINTS (AbstractEndpoint subclasses)
#endpoints:
#  enabled: true

# Tesseract OCR
tesseract:
  traineddata:
    path: C:\\Tess4J\\traineddata\\tessdata
    lang: jpn

retention:
  persontovisit:
    period: 36
    logfilepath: log/persontovisit.log

slack:
  token: xoxb-xxxxxxxxxxxx-xxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx
  channel: Cxxxxxxxxxx
  url: https://slack.com/api/files.upload
