# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 9000

spring:
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true
    cache: false
# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: messages
    #cache-seconds: -1
    encoding: UTF-8
# MONGODB (MongoProperties)
  data:
    mongodb:
      host: xxx # hostname
      port: 27017
      uri: xxx # connection URL
      database: mongovwdb
#      authentication-database: mongovwdb
#      grid-fs-database:
      username: xxx
      password: xxx
      #repositories:
        #enabled: true  # if spring data repository support is enabled

# ENDPOINTS (AbstractEndpoint subclasses)
#endpoints:
#  enabled: true