# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 8080

spring:
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true
    cache: false
# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: messages
#    cache-seconds: -1
    encoding: UTF-8
# MONGODB (MongoProperties)
  data:
    mongodb:
      host: cluster0-cf1b0.gcp.mongodb.net
      port: 27017
      uri: mongodb+srv://app:kAz54fgSlnACwxIi@cluster0-cf1b0.gcp.mongodb.net/test?retryWrites=true&w=majority
      database: database
#      authentication-database: mongovwdb
#      grid-fs-database:
      username: app
      password: kAz54fgSlnACwxIi
#      repositories:
#        enabled: true  # if spring data repository support is enabled

# ENDPOINTS (AbstractEndpoint subclasses)
#endpoints:
#  enabled: true

# Tesseract OCR
tesseract:
  traineddata:
    path: src/main/resources/static/traineddata/tessdata
    lang: jpn

retention:
  persontovisit:
    period: 36
    logfilepath: log1/persontovisit.log
