# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 8080

spring:
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true
    cache: false
# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: messages
#    cache-seconds: -1
    encoding: UTF-8
# MONGODB (MongoProperties)
  data:
    mongodb:
      host: xxx ### change
      port: 0 ### change
      uri: xxx ### change
      database: database
#      authentication-database: mongovwdb
#      grid-fs-database:
      username: xxx ### change
      password: xxx ### change
#      repositories:
#        enabled: true  # if spring data repository support is enabled

# ENDPOINTS (AbstractEndpoint subclasses)
#endpoints:
#  enabled: true

# Tesseract OCR
tesseract:
  traineddata:
    path: src/main/resources/static/traineddata/tessdata
    lang: jpn

retention:
  persontovisit:
    period: 36
    logfilepath: log/persontovisit.log
